someNumbers.foreach(x => println(x))
//the above function can be rewritten as
someNumbers.foreach(println _)
//given below function
def sum(a: Int, b: Int, c: Int) = a + b + c
//following expression applies sum to arguments 1, 2 and 3
sum(1, 2, 3)
//to create a partially applied function involving "sum", in which you supply none of the three required parameters, you just place an underscore after "sum"
//the resulting function can be stored in a variable
val a = sum _
a(1, 2, 3)
//This function value is an instance of a class generated by the Scala compiler from sum _, the partially applied function expression.
//The class generated by the compiler has an apply method that takes three arguments.
a.apply(1, 2, 3)
